[pytest]
# Solve "import file mismatch" for files with the same name
addopts = --import-mode=importlib
# Only look for tests in the tests/ directory
testpaths = tests
# Ignore directories that contain scripts/experiments not meant for pytest
norecursedirs = experiments rh flux_test YMFormal
